//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortestFlight
{
    using System;
    using System.Collections.Generic;
    
    public partial class airline
    {
        public int airline_ID { get; set; }
        public string airline_name { get; set; }
        public string ICAO { get; set; }
        public string country { get; set; }
        public string active { get; set; }
    }
}
