//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortestFlight
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShortestFlightEntities : DbContext
    {
        public ShortestFlightEntities()
            : base("name=ShortestFlightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<airport> airports { get; set; }
        public DbSet<route> routes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<airline> airlines { get; set; }
    }
}
