//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortestFlight
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        public int route_ID { get; set; }
        public Nullable<int> distance { get; set; }
        public Nullable<int> from_OID { get; set; }
        public Nullable<int> to_OID { get; set; }
    
        public virtual airport airport { get; set; }
    }
}
